# Generated by Django 5.1.2 on 2024-10-19 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantaty',
            field=models.DecimalField(decimal_places=3, default=True, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 19, 5, 4, 38, 175403)),
        ),
    ]
