# Generated by Django 5.1.2 on 2024-10-19 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0002_product_notes_product_quantaty_alter_product_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='package_weight',
            field=models.DecimalField(decimal_places=3, default=True, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 19, 5, 5, 19, 416022)),
        ),
    ]
