# Generated by Django 5.1.2 on 2024-10-19 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0003_product_package_weight_alter_product_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 19, 5, 7, 41, 848456)),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantaty',
            field=models.DecimalField(decimal_places=0, default=True, max_digits=10),
        ),
    ]
